- name: Install pipx package
  apt: name=pipx state=present
  become: yes
- name: Install docker-compose through pipx
  command: pipx install docker-compose
  args:
    creates: "{{ home }}/.local/bin/docker-compose"
- name: Install docker-compose for python
  pip: name="docker-compose" state=present
