version: '3.8'

# https://github.com/vegasbrianc/prometheus

services:

  ## https://dev.to/ablx/minimal-prometheus-setup-with-docker-compose-56mp
  prometheus:
    image: quay.io/prometheus/prometheus:v2.29.2
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      monitoring_net:
        ipv4_address: 10.0.10.2
      pihole_net:
        ipv4_address: 10.0.0.6

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.2.2
    container_name: node_exporter
    # network_mode: host
    # pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      monitoring_net:
        ipv4_address: 10.0.10.3

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    user: "472"
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped
    networks:
      monitoring_net:
        ipv4_address: 10.0.10.4

  snmp_exporter:
    image: quay.io/ricardbejarano/snmp_exporter:0.19.0
    container_name: snmp_exporter
    ports:
      - 9116:9116
    # volumes:
      # - ./snmp/snmp.yml:/snmp.yml
    networks:
      monitoring_net:
        ipv4_address: 10.0.10.5
    restart: unless-stopped

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  monitoring_net:
    driver: bridge
    name: monitoring_net
    ipam:
     config:
       - subnet: 10.0.10.0/24
  pihole_net:
    external: true
    name: pihole_net
